# Generated by Django 4.2.7 on 2023-11-24 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='producto',
        ),
    ]
